sudo: required
language: generic
services:
  - docker
  
before_install:
  - docker build -t mihir/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run mihir/react-test npm test -- --coverage
  
after_success:
  - docker build -t mihir/multi-client ./client
  - docker build -t mihir/multi-nginx ./nginx
  - docker build -t mihir/multi-server ./server
  - docker build -t mihir/multi-worker ./worker
  
  #Log in to CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push mihir/multi-client
  - docker push mihir/multi-nginx
  - docker push mihir/multi-server
  - docker push mihir/multi-worker
